name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to destroy? (dev/stage/prod)"
        required: true
        default: "dev"

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}   # 👈 links to GitHub Environments

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Destroy
      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file=env/${{ github.event.inputs.environment }}.tfvars